services:
  - type: web
    name: resume-analyzer
    env: python
    buildCommand: |
      pip install -r backend/requirements.txt
      cd frontend && npm ci && npm run build
    startCommand: cd backend/src && uvicorn agent.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: PYTHONPATH
        value: /opt/render/project/repo/backend/src
